#!/bin/bash

#> [ns]=? [selector]=? [value]=? [port]=? [node]=?

kubectl create ns $NS --dry-run=client -o yaml | kubectl apply -f -

cat << EOF | kubectl apply -n $NS -f -
kind: Service
apiVersion: v1
metadata:
  name: ${NS}-nodeport
spec:
  type: NodePort
  selector:
    ${SELECTOR}: ${VALUE}
  ports:
  - port: ${PORT}
    targetPort: ${PORT}
    nodePort: ${NODE}
EOF