#!/bin/bash

#>
SYS_HOSTNAME=$(hostnamectl hostname)
echo "SYS_HOSTNAME : $SYS_HOSTNAME"

sed -i "s|SYS_HOSTNAME|$SYS_HOSTNAME|g" /etc/otelcol-contrib/config.yaml
sed -i "s|system.kueb.io|$SYS_HOSTNAME.kueb.io|g" /etc/systemd/system/k3s.service
echo "done" > /root/.done