#!/bin/bash

#> [ns]=cert-manager

cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: $NS
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: $NS
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  targetNamespace: $NS
  valuesContent: |-
    crds.enabled: true
EOF