#!/bin/bash

#> [ns]=cert-manager [dns]=admin.pilet.cloud

cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: $NS
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: $NS
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  targetNamespace: $NS
  valuesContent: |-
    crds:
      enabled: true
EOF

sleep 30s
cat <<EOF | kubectl apply -n $NS -f -
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key-secret
type: Opaque
stringData:
  api-key: ${CF_API_KEY}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme
spec:
  acme:
    email: ${CF_API_EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme
    solvers:
    - dns01:
        cloudflare:
          email: ${CF_API_EMAIL}
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain
spec:
  secretName: tls-domain
  dnsNames:
  - ${DNS}
  issuerRef:
    name: acme
    kind: ClusterIssuer
    group: cert-manager.io
EOF