#!/bin/bash

#>
function click() {
  kubectl exec -ti -n clickhouse --container clickhouse chi-click-main-0-0-0 -- clickhouse-client "$@"
}

click --query "CREATE DATABASE IF NOT EXISTS otel"
click -d otel --query "CREATE TABLE IF NOT EXISTS otel_traces (
               Timestamp DateTime64(9) CODEC(Delta, ZSTD(1)),
               TraceId String CODEC(ZSTD(1)),
               SpanId String CODEC(ZSTD(1)),
               ParentSpanId String CODEC(ZSTD(1)),
               TraceState String CODEC(ZSTD(1)),
               SpanName LowCardinality(String) CODEC(ZSTD(1)),
               SpanKind LowCardinality(String) CODEC(ZSTD(1)),
               ServiceName LowCardinality(String) CODEC(ZSTD(1)),
               ResourceAttributes Map(LowCardinality(String), String) CODEC(ZSTD(1)),
               ScopeName String CODEC(ZSTD(1)),
               ScopeVersion String CODEC(ZSTD(1)),
               SpanAttributes Map(LowCardinality(String), String) CODEC(ZSTD(1)),
               Duration UInt64 CODEC(ZSTD(1)),
               StatusCode LowCardinality(String) CODEC(ZSTD(1)),
               StatusMessage String CODEC(ZSTD(1)),
               Events Nested (
                   Timestamp DateTime64(9),
                   Name LowCardinality(String),
                   Attributes Map(LowCardinality(String), String)
               ) CODEC(ZSTD(1)),
               Links Nested (
                   TraceId String,
                   SpanId String,
                   TraceState String,
                   Attributes Map(LowCardinality(String), String)
               ) CODEC(ZSTD(1)),
               INDEX idx_trace_id TraceId TYPE bloom_filter(0.001) GRANULARITY 1,
               INDEX idx_res_attr_key mapKeys(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
               INDEX idx_res_attr_value mapValues(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
               INDEX idx_span_attr_key mapKeys(SpanAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
               INDEX idx_span_attr_value mapValues(SpanAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
               INDEX idx_duration Duration TYPE minmax GRANULARITY 1
           ) ENGINE = MergeTree()
           PARTITION BY toDate(Timestamp)
           ORDER BY (ServiceName, SpanName, toDateTime(Timestamp))
           TTL toDate(Timestamp) + toIntervalDay(180)
           SETTINGS index_granularity=8192, ttl_only_drop_parts = 1"

click -d otel --query "CREATE TABLE IF NOT EXISTS otel_metrics_gauge
           (
               ResourceAttributes    Map(LowCardinality(String), String) CODEC (ZSTD(1)),
               ResourceSchemaUrl     String CODEC (ZSTD(1)),
               ScopeName             String CODEC (ZSTD(1)),
               ScopeVersion          String CODEC (ZSTD(1)),
               ScopeAttributes       Map(LowCardinality(String), String) CODEC (ZSTD(1)),
               ScopeDroppedAttrCount UInt32 CODEC (ZSTD(1)),
               ScopeSchemaUrl        String CODEC (ZSTD(1)),
               ServiceName           LowCardinality(String) CODEC (ZSTD(1)),
               MetricName            String CODEC (ZSTD(1)),
               MetricDescription     String CODEC (ZSTD(1)),
               MetricUnit            String CODEC (ZSTD(1)),
               Attributes            Map(LowCardinality(String), String) CODEC (ZSTD(1)),
               StartTimeUnix         DateTime64(9) CODEC (Delta, ZSTD(1)),
               TimeUnix              DateTime64(9) CODEC (Delta, ZSTD(1)),
               Value                 Float64 CODEC (ZSTD(1)),
               Flags                 UInt32 CODEC (ZSTD(1)),
               Exemplars             Nested(FilteredAttributes Map(LowCardinality(String), String),
                                         TimeUnix DateTime64(9),
                                         Value Float64,
                                         SpanId String,
                                         TraceId String) CODEC (ZSTD(1)),
               INDEX idx_res_attr_key mapKeys(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
               INDEX idx_res_attr_value mapValues(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
               INDEX idx_scope_attr_key mapKeys(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
               INDEX idx_scope_attr_value mapValues(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
               INDEX idx_attr_key mapKeys(Attributes) TYPE bloom_filter(0.01) GRANULARITY 1,
               INDEX idx_attr_value mapValues(Attributes) TYPE bloom_filter(0.01) GRANULARITY 1
           ) ENGINE = MergeTree
                 PARTITION BY toDate(TimeUnix)
                 ORDER BY (ServiceName, MetricName, Attributes, toUnixTimestamp64Nano(TimeUnix))
                 TTL toDateTime(TimeUnix) + toIntervalDay(180)
                 SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1"

  click --query "CREATE TABLE IF NOT EXISTS otel_metrics_sum (
          ResourceAttributes Map(LowCardinality(String), String) CODEC(ZSTD(1)),
          ResourceSchemaUrl String CODEC(ZSTD(1)),
          ScopeName String CODEC(ZSTD(1)),
          ScopeVersion String CODEC(ZSTD(1)),
          ScopeAttributes Map(LowCardinality(String), String) CODEC(ZSTD(1)),
          ScopeDroppedAttrCount UInt32 CODEC(ZSTD(1)),
          ScopeSchemaUrl String CODEC(ZSTD(1)),
          ServiceName LowCardinality(String) CODEC(ZSTD(1)),
          MetricName String CODEC(ZSTD(1)),
          MetricDescription String CODEC(ZSTD(1)),
          MetricUnit String CODEC(ZSTD(1)),
          Attributes Map(LowCardinality(String), String) CODEC(ZSTD(1)),
          StartTimeUnix DateTime64(9) CODEC(Delta, ZSTD(1)),
          TimeUnix DateTime64(9) CODEC(Delta, ZSTD(1)),
          Value Float64 CODEC(ZSTD(1)),
          Flags UInt32  CODEC(ZSTD(1)),
          Exemplars Nested (
            FilteredAttributes Map(LowCardinality(String), String),
            TimeUnix DateTime64(9),
            Value Float64,
            SpanId String,
            TraceId String
            ) CODEC(ZSTD(1)),
          AggregationTemporality Int32 CODEC(ZSTD(1)),
          IsMonotonic Boolean CODEC(Delta, ZSTD(1)),
          INDEX idx_res_attr_key mapKeys(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
          INDEX idx_res_attr_value mapValues(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
          INDEX idx_scope_attr_key mapKeys(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
          INDEX idx_scope_attr_value mapValues(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
          INDEX idx_attr_key mapKeys(Attributes) TYPE bloom_filter(0.01) GRANULARITY 1,
          INDEX idx_attr_value mapValues(Attributes) TYPE bloom_filter(0.01) GRANULARITY 1
          ) ENGINE = MergeTree()
          TTL toDateTime("TimeUnix") + toIntervalDay(180)
          PARTITION BY toDate(TimeUnix)
          ORDER BY (ServiceName, MetricName, Attributes, toUnixTimestamp64Nano(TimeUnix))
          SETTINGS index_granularity=8192, ttl_only_drop_parts = 1"
