#!/bin/bash

#> [ns]=clickhouse

kubectl create ns $NS --dry-run=client -o yaml | kubectl apply -f -

cat <<EOF | kubectl apply -n $NS -f -
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otel
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /v1/logs
            pathType: Prefix
            backend:
              service:
                name: otel-opentelemetry-collector
                port:
                  number: 4318
          - path: /v1/traces
            pathType: Prefix
            backend:
              service:
                name: otel-opentelemetry-collector
                port:
                  number: 4318
          - path: /v1/metrics
            pathType: Prefix
            backend:
              service:
                name: otel-opentelemetry-collector
                port:
                  number: 4318

EOF