#!/bin/bash

#> [ns]=clickhouse

kubectl create ns $NS --dry-run=client -o yaml | kubectl apply -f -

cat << EOF | kubectl apply -n $NS -f -
kind: Service
apiVersion: v1
metadata:
  name: clickhouse-nodeport
spec:
  type: NodePort
  selector:
    clickhouse.altinity.com/chi: click
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30900
  - protocol: TCP
    port: 8123
    targetPort: 8123
    nodePort: 30812
EOF