#!/bin/bash

#> [ns]=clickhouse

kubectl create ns $NS --dry-run=client -o yaml | kubectl apply -f -

cat << EOF | kubectl apply -n $NS -f -
kind: Service
apiVersion: v1
metadata:
  name: clickhouse-nodeport
spec:
  type: NodePort
  selector:
    clickhouse.altinity.com/chi: click
  ports:
  - protocol: TCP
    name: jdbc
    port: 8123
    targetPort: 8123
    nodePort: 30812
EOF

cat << EOF | kubectl apply -n $NS -f -
kind: Service
apiVersion: v1
metadata:
  name: clickhouse-collector-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: otel
  ports:
  - protocol: TCP
    name: otel
    port: 4317
    targetPort: 4317
    nodePort: 30431
EOF