#!/bin/bash

#> [ns]=tools

kubectl create ns $NS

cat<<EOF | kubectl apply -n $NS -f -
apiVersion: v1
kind: Pod
metadata:
  name: console
  labels:
    app: console
spec:
  containers:
  - name: console
    image: ubuntu:24.04
    args:
      - /bin/sh
      - -c
      - while :; do sleep 2073600; done
EOF


