#!/bin/bash

#> [ns]=tools

kubectl create ns $NS
with kube configure docker --ns $NS

cat<<EOF | kubectl apply -n $NS -f -
apiVersion: v1
kind: Pod
metadata:
  name: console
  labels:
    app: console
spec:
  containers:
  - name: console
    image: busybox
    securityContext:
      privileged: true
    imagePullPolicy: IfNotPresent
  restartPolicy: Always\
EOF