#!/bin/bash

#> [ns]=kafka [name]=main [disk]=100 [replicas]=1

kubectl create ns $NS
kubectl create -f "https://strimzi.io/install/latest?namespace=$NS" -n $NS

sleep 20s

cat <<EOF | kubectl apply -n $NS -f -
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: $NAME
spec:
  kafka:
    version: 3.7.0
    replicas: $REPLICAS
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.7"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: ${DISK}Gi
        deleteClaim: false
  zookeeper:
    replicas: $REPLICAS
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
EOF
