#!/bin/bash

#> [ns]=kpow

kubectl create ns $NS --dry-run=client -o yaml | kubectl apply -f -
cat <<EOF | kubectl apply -n $NS -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpow
  labels:
    app: kpow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpow

  template:
    metadata:
      labels:
        app: kpow
    spec:
      containers:
      - name: kpow
        image: factorhouse/kpow-ce:latest
        env:
        - name: LICENSE_ID
          value: f95015d3-c343-4214-8950-3b16ecf62488
        - name: LICENSE_CODE
          value: KPOW_COMMUNITY
        - name: LICENSEE
          value: Aleksandr Potapov
        - name: LICENSE_EXPIRY
          value: 2025-12-13
        - name: LICENSE_SIGNATURE
          value: 21364C7EED9FA99E055D674BA6BEFE6D4E8C88364D2D9353E7E2035D36A7505D4A19BEB9F197F87C18E7D009EA096B441BFC2C7B6D9F99341079CA12B256F6FC9CF35EA57B37B5566901759D7119F6D96B47FBC3D859A469CB6C68F9E3D908EDC8BAD8E6AF7439F41AE20C23712425830BB48C21FC6B1F3ADF48AEE6EDC10A18
        - name: BOOTSTRAP
          value: main-kafka-bootstrap.kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: kpow
spec:
  type: ClusterIP
  ports:
  - name: webui
    port: 3000
    targetPort: 3000
  selector:
    app: kpow
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: kpow-prefix
spec:
  stripPrefix:
    prefixes:
    - "/kpow"
    forceSlash: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kpow-route
spec:
  entryPoints:
  - web
  routes:
  - match: PathPrefix(``/kpow``)
    kind: Rule
    services:
    - name: kpow
      port: 3000
EOF