#!/bin/bash

#> [ns]=otel [key]=030f250aea0ff3dba75e8ba404d5ad47FFFFNRAL

kubectl create ns $NS --dry-run=client -o yaml | kubectl apply -f -
helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
helm repo update

cat <<EOF > /tmp/values.yml
mode: daemonset
image:
  repository: "otel/opentelemetry-collector-contrib"

presets:
  logsCollection:
    enabled: true

  kubernetesAttributes:
    enabled: false

  hostMetrics:
    enabled: true

  kubeletMetrics:
    enabled: true

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch:
      send_batch_max_size: 10000
      timeout: 10s

  exporters:
    otlphttp:
      endpoint: https://otlp.nr-data.net
      headers:
        api-key: $KEY

  service:
   pipelines:
     traces:
       receivers: [otlp]
       processors: [batch]
       exporters: [otlphttp]
     metrics:
       receivers: [otlp]
       processors: [batch]
       exporters: [otlphttp]
     logs:
       receivers: [otlp]
       processors: [batch]
       exporters: [otlphttp]
EOF

helm install otel open-telemetry/opentelemetry-collector --namespace $NS --values /tmp/values.yml