#!/bin/bash

#> [ns]=otel

kubectl create ns $NS --dry-run=client -o yaml | kubectl apply -f -
helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
helm repo update

cat <<EOF > /tmp/values.yml
mode: daemonset
image:
  repository: "otel/opentelemetry-collector-contrib"

service:
  enabled: true

presets:
  hostMetrics:
    enabled: true

config:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch:
      send_batch_max_size: 10000
      timeout: 10s

  exporters:
    nop:
    kafka:
      brokers:
        - kafka-service.kafka:9092
      logs:
        encoding: otlp_json
      traces:
        encoding: otlp_json
      metrics:
        encoding: otlp_json

  service:
   pipelines:
     traces:
       receivers: [otlp]
       processors: [batch]
       exporters: [kafka]
     metrics:
       receivers: [otlp]
       processors: [batch]
       exporters: [kafka]
     logs:
       receivers: [otlp]
       processors: [batch]
       exporters: [nop]
EOF

helm install otel open-telemetry/opentelemetry-collector --namespace $NS --values /tmp/values.yml