#!/bin/bash

#> [ns]=postgres [disk]=100

kubectl create ns $NS --dry-run=client -o yaml | kubectl apply -f -

cat <<EOF | tee /tmp/postgres.yaml
global:
  postgresql:
    auth:
      postgresPassword: par0l2010
persistence:
  size: ${DISK}Gi
EOF

helm install postgres --values /tmp/postgres.yaml --namespace $NS oci://registry-1.docker.io/bitnamicharts/postgresql

echo "!> url=postgres.postgres"
echo "!> port=5432"
echo "!> username=postgres"
echo "!> password=par0l2010"
echo "!> disk=$DISK"
